const IMG='https://images.unsplash.com/';
const products=[
{id:1,name:'Celeste Tennis Necklace',cat:'women',type:'Necklace',tags:['necklaces','gift'],price:2899,old:3499,rating:4.9,img:IMG+'photo-1599643478518-a784e5dc4c8f?auto=format&fit=crop&w=800&q=85',badge:'BESTSELLER'},
{id:2,name:'Solara Halo Ring',cat:'women',type:'Ring',tags:['rings','gift'],price:2199,old:2799,rating:4.8,img:IMG+'photo-1605100804763-247f67b3557e?auto=format&fit=crop&w=800&q=85',badge:'NEW'},
{id:3,name:'Luna Drop Earrings',cat:'women',type:'Earrings',tags:['earrings','gift'],price:1799,old:2199,rating:4.7,img:IMG+'photo-1635767798638-3e25273a8236?auto=format&fit=crop&w=800&q=85'},
{id:4,name:'Pearl Muse Bracelet',cat:'women',type:'Bracelet',tags:['bracelets'],price:1999,old:2499,rating:4.8,img:IMG+'photo-1619119069152-a2b331eb392a?auto=format&fit=crop&w=800&q=85'},
{id:5,name:'Astra Pendant Chain',cat:'women',type:'Necklace',tags:['necklaces'],price:2399,old:2999,rating:4.6,img:IMG+'photo-1617038220319-276d3cfab638?auto=format&fit=crop&w=800&q=85'},
{id:6,name:'Eden Stack Ring',cat:'women',type:'Ring',tags:['rings'],price:1599,old:1999,rating:4.7,img:IMG+'photo-1627293509201-cd8d132b0b0d?auto=format&fit=crop&w=800&q=85'},
{id:7,name:'Mira Gold Hoops',cat:'women',type:'Earrings',tags:['earrings'],price:1499,old:1899,rating:4.8,img:IMG+'photo-1535632066927-ab7c9ab60908?auto=format&fit=crop&w=800&q=85'},
{id:8,name:'Serene Cuff',cat:'women',type:'Bracelet',tags:['bracelets','gift'],price:1899,old:2299,rating:4.6,img:IMG+'photo-1573408301185-9146fe634ad0?auto=format&fit=crop&w=800&q=85'},
{id:9,name:'Noir Signet Ring',cat:'men',type:'Ring',tags:['rings'],price:2299,old:2799,rating:4.9,img:IMG+'photo-1603561596112-db0d9c7b5f8b?auto=format&fit=crop&w=800&q=85',badge:'MEN'},
{id:10,name:'Atlas Chain',cat:'men',type:'Chain',tags:['necklaces'],price:2699,old:3299,rating:4.8,img:IMG+'photo-1515562141207-7a88fb7ce338?auto=format&fit=crop&w=800&q=85',badge:'MEN'},
{id:11,name:'Cobalt Link Bracelet',cat:'men',type:'Bracelet',tags:['bracelets'],price:1999,old:2499,rating:4.7,img:IMG+'photo-1611652022419-a9419f74343d?auto=format&fit=crop&w=800&q=85',badge:'MEN'},
{id:12,name:'Monarch Cuff',cat:'men',type:'Cuff',tags:['bracelets'],price:1799,old:2199,rating:4.6,img:IMG+'photo-1573408301185-9146fe634ad0?auto=format&fit=crop&w=800&q=85',badge:'MEN'},
{id:13,name:'Sterling Edge Ring',cat:'men',type:'Ring',tags:['rings'],price:1899,old:2399,rating:4.8,img:IMG+'photo-1605100804763-247f67b3557e?auto=format&fit=crop&w=800&q=85',badge:'MEN'},
{id:14,name:'Orion Layered Chain',cat:'men',type:'Chain',tags:['necklaces'],price:2999,old:3599,rating:4.7,img:IMG+'photo-1617038220319-276d3cfab638?auto=format&fit=crop&w=800&q=85',badge:'MEN'},
{id:15,name:'Vega Minimal Bracelet',cat:'men',type:'Bracelet',tags:['bracelets','gift'],price:1599,old:1999,rating:4.5,img:IMG+'photo-1619119069152-a2b331eb392a?auto=format&fit=crop&w=800&q=85'},
{id:16,name:'Royal Crest Ring',cat:'men',type:'Ring',tags:['rings','gift'],price:2499,old:2999,rating:4.9,img:IMG+'photo-1603561596112-db0d9c7b5f8b?auto=format&fit=crop&w=800&q=85',badge:'LIMITED'},
{id:17,name:'Amara Pearl Set',cat:'women',type:'Jewellery Set',tags:['gift'],price:3299,old:4299,rating:4.9,img:'https://cdn.salla.sa/KAdxD/090a188b-eb83-425f-a7aa-4ecf2bf7064b-800.16934801016x1000-Czcotn7TeukKF0wJ2CC2iCmVoA22Ar7UiXrLXvW4.jpg',badge:'SET'},
{id:18,name:'Auralis Celebration Set',cat:'women',type:'Jewellery Set',tags:['gift'],price:3899,old:4999,rating:4.8,img:'https://voguejewels.in/cdn/shop/files/Auralis_Set.jpg',badge:'GIFT'},
{id:19,name:'Midnight Solitaire',cat:'women',type:'Ring',tags:['rings','gift'],price:2699,old:3199,rating:4.9,img:'https://10xproductpics.com/assets/jewelry-hero-C0gYmSPZ.jpg',badge:'ICONIC'},
{id:20,name:'Golden Arc Pendant',cat:'women',type:'Pendant',tags:['necklaces'],price:1699,old:2099,rating:4.6,img:'https://hanagold.vn/assets/img/products/img_banner_big_01.png'},
{id:21,name:'Heritage Floral Necklace',cat:'women',type:'Necklace',tags:['necklaces','gift'],price:4599,old:5299,rating:4.9,img:'https://parashabora.com/cdn/shop/collections/DSC07927.jpg?v=1718977888',badge:'HERITAGE'},
{id:22,name:'Silver Grace Ensemble',cat:'women',type:'Jewellery Set',tags:['gift'],price:3499,old:4199,rating:4.7,img:'https://cdn.myikas.com/images/10eafdf6-9ca9-4be9-b2af-3488fc911fe7/982f9910-12bb-4f8c-8389-41f3b93e5704/1080/londonacs-set-03.webp',badge:'SET'},
{id:23,name:'Classic Gold Four-Piece',cat:'women',type:'Jewellery Set',tags:['gift'],price:4199,old:5199,rating:4.8,img:'https://cdn.prosystem.com.bd/images/AMISHEE/DSC03285-2179749d5-8c25-4347-b3dd-96a54a46f345.jpg',badge:'SET'},
{id:24,name:'Dewdrop Diamond Edit',cat:'women',type:'Jewellery Set',tags:['gift'],price:3799,old:4599,rating:4.8,img:'https://media.zid.store/thumbs/c330bdf6-d372-43c3-99d3-a72da9e4ad63/cb8fc7e8-a364-44a3-af33-9bdb10559193-thumbnail-1000x1000.png',badge:'SET'}
];
let cart=JSON.parse(localStorage.getItem('aurumCart')||'[]'), currentFilter='all', coupon=0;
const $=s=>document.querySelector(s), $$=s=>document.querySelectorAll(s);
const money=n=>'₹'+n.toLocaleString('en-IN');
function save(){localStorage.setItem('aurumCart',JSON.stringify(cart));renderCart()}
function renderProducts(){const grid=$('#productGrid');let list=products.filter(p=>currentFilter==='all'||p.cat===currentFilter||p.tags.includes(currentFilter));if(currentFilter==='all'&&!window.showAll)list=list.slice(0,12);grid.innerHTML=list.map((p,i)=>`<article class="product-card" style="animation-delay:${i*35}ms"><div class="product-image"><${p.badge?`span class="badge">${p.badge}</span>`:''}<button class="wish" onclick="toggleWish(this)">♡</button><img loading="lazy" src="${p.img}" alt="${p.name}" onerror="this.src='https://images.unsplash.com/photo-1515562141207-7a88fb7ce338?auto=format&fit=crop&w=800&q=80'"></div><div class="product-info"><span class="type">${p.type} · ${p.cat==='men'?'Men':'Women'}</span><h3>${p.name}</h3><div class="price-row"><span class="price">${money(p.price)} <del>${money(p.old)}</del></span><span class="stars">★★★★★ ${p.rating}</span></div><button class="add" onclick="addToCart(${p.id})">ADD TO BAG</button></div></article>`).join('');}
function addToCart(id){let item=cart.find(x=>x.id===id);if(item)item.qty++;else cart.push({id,qty:1});save();toast('Added to your bag ✦');}
function renderCart(){const items=$('#cartItems');$('#cartCount').textContent=cart.reduce((a,b)=>a+b.qty,0);if(!cart.length){items.innerHTML='<div class="empty"><div style="font-size:38px">◇</div><h3>Your bag is waiting</h3><p>Add a few pieces you love and they will appear here.</p><button class="btn btn-outline" onclick="closeAll()">Continue shopping</button></div>';}else items.innerHTML=cart.map(x=>{let p=products.find(a=>a.id===x.id);return `<div class="cart-item"><img src="${p.img}" alt="${p.name}"><div><h4>${p.name}</h4><small>${money(p.price)}</small><div class="qty"><button onclick="changeQty(${p.id},-1)">−</button><span>${x.qty}</span><button onclick="changeQty(${p.id},1)">+</button></div></div><strong>${money(p.price*x.qty)}</strong></div>`}).join('');let sub=cart.reduce((a,x)=>a+products.find(p=>p.id===x.id).price*x.qty,0), ship=sub?sub>=2999?0:99:0, total=Math.max(0,sub+ship-coupon);$('#subtotal').textContent=money(sub);$('#shipping').textContent=ship?money(ship):'FREE';$('#cartTotal').textContent=money(total)}
function changeQty(id,d){let x=cart.find(a=>a.id===id);if(!x)return;x.qty+=d;if(x.qty<=0)cart=cart.filter(a=>a.id!==id);save()}
function openDrawer(){closeAll();$('#overlay').style.display='block';$('#cartDrawer').classList.add('open')}
function closeAll(){$('#overlay').style.display='none';$('#cartDrawer').classList.remove('open');$$('.modal').forEach(m=>m.classList.remove('open'));$('#searchPanel').classList.remove('open');}
function toast(t){const e=$('#toast');e.textContent=t;e.classList.add('show');setTimeout(()=>e.classList.remove('show'),2500)}
function setFilter(f){currentFilter=f;$$('.filter').forEach(x=>x.classList.toggle('active',x.dataset.filter===f));renderProducts();document.querySelector('#shop').scrollIntoView({behavior:'smooth'});}
function openAuth(){closeAll();$('#overlay').style.display='block';$('#authModal').classList.add('open')}
function openQuiz(){closeAll();$('#overlay').style.display='block';$('#quizModal').classList.add('open');quizStep=0;quizAnswers=[];renderQuiz()}
let quizStep=0,quizAnswers=[];const qs=[['What do you wear most?',['Minimal everyday','Statement pieces','Traditional','Smart & masculine']],['Pick a finish',['Yellow gold','Silver','Rose gold','Mixed metals']],['Your usual vibe?',['Quiet luxury','Glamorous','Classic','Street smart']]];
function renderQuiz(){const b=$('#quizBody');if(quizStep<qs.length){let q=qs[quizStep];b.innerHTML=`<div class="quiz-q">${q[0]}</div><div class="quiz-options">${q[1].map(o=>`<button onclick="quizAnswer('${o}')">${o}</button>`).join('')}</div><p style="color:#999;font-size:10px;margin-top:15px">${quizStep+1} / ${qs.length}</p>`}else{let men=quizAnswers.includes('Smart & masculine'),rec=products.filter(p=>p.cat===(men?'men':'women')).slice(0,4);b.innerHTML=`<div style="background:#f6efe6;padding:22px;margin-top:15px"><p class="eyebrow">YOUR EDIT</p><h3 style="font-family:'Playfair Display';font-size:28px;margin:0 0 8px">${men?'The Modern Gentleman':'The Everyday Muse'}</h3><p style="color:#756f68;font-size:12px">We matched your answers with pieces that fit your style. Start with these.</p></div><div class="quiz-options" style="margin-top:15px">${rec.map(p=>`<button onclick="addToCart(${p.id})"><b>${p.name}</b><br><small>${money(p.price)}</small></button>`).join('')}</div><button class="btn btn-dark full" style="margin-top:15px" onclick="closeAll();setFilter('${men?'men':'women'}')">Shop my edit</button>`}}
function quizAnswer(a){quizAnswers.push(a);quizStep++;renderQuiz()}
function checkout(){if(!cart.length){toast('Your bag is empty');return}closeAll();$('#overlay').style.display='block';$('#checkoutModal').classList.add('open');checkoutStep=1;renderCheckout()}
let checkoutStep=1,payment='UPI';
function renderCheckout(){const b=$('#checkoutBody');let sub=cart.reduce((a,x)=>a+products.find(p=>p.id===x.id).price*x.qty,0),ship=sub>=2999?0:99,total=Math.max(0,sub+ship-coupon);if(checkoutStep===1)b.innerHTML=`<div class="checkout-form"><h2>Where should we deliver?</h2><div class="form-grid"><input id="name" placeholder="Full name" required><input id="phone" placeholder="Mobile number" required><input id="address" placeholder="House / street address" required><input id="city" placeholder="City" required><input id="pin" placeholder="PIN code" required><select id="state"><option>State / UT</option><option>Maharashtra</option><option>Delhi</option><option>Karnataka</option><option>Gujarat</option><option>West Bengal</option></select></div><div class="checkout-summary"><div class="summary"><span>Items</span><b>${money(sub)}</b></div><div class="summary"><span>Shipping</span><b>${ship?'₹99':'FREE'}</b></div><div class="summary total"><span>Total</span><b>${money(total)}</b></div></div><button class="btn btn-dark full" onclick="checkoutStep=2;renderCheckout()">Continue to payment →</button></div>`;else if(checkoutStep===2)b.innerHTML=`<div class="checkout-form"><h2>Choose payment</h2><div class="payment-options"><button class="${payment==='UPI'?'active':''}" onclick="payment='UPI';renderCheckout()">UPI</button><button class="${payment==='Card'?'active':''}" onclick="payment='Card';renderCheckout()">Card</button><button class="${payment==='COD'?'active':''}" onclick="payment='COD';renderCheckout()">Cash on delivery</button></div>${payment==='UPI'?'<input placeholder="UPI ID (demo)">':payment==='Card'?'<div class="form-grid"><input placeholder="Card number"><input placeholder="MM / YY"><input placeholder="Name on card"><input placeholder="CVV"></div>':'<div style="background:#f6efe6;padding:15px;font-size:12px">Pay the delivery executive when your order arrives. A small COD fee may apply on real orders.</div>'}<div class="checkout-summary"><div class="summary total"><span>Payable</span><b>${money(total)}</b></div></div><button class="btn btn-dark full" onclick="checkoutStep=3;renderCheckout()">Review order →</button></div>`;else b.innerHTML=`<div class="checkout-form"><h2>Review & place order</h2><div class="checkout-summary"><p><b>Delivery</b><br><span id="reviewName">Your details</span></p><p><b>Payment</b><br>${payment}</p><div class="summary total"><span>Total</span><b>${money(total)}</b></div></div><button class="btn btn-dark full" onclick="placeOrder()">Place order · ${money(total)}</button><p style="font-size:10px;color:#999;text-align:center;margin-top:12px">Demo checkout — no real payment is processed.</p></div>`;$$('.checkout-steps span').forEach((s,i)=>s.classList.toggle('active',i<checkoutStep))}
function placeOrder(){let id='AU'+Math.floor(100000+Math.random()*900000);cart=[];coupon=0;save();$('#checkoutBody').innerHTML=`<div class="success"><div class="check">✓</div><p class="eyebrow">ORDER CONFIRMED</p><h2 style="font-family:'Playfair Display';font-size:34px">Thank you for shopping with us.</h2><p style="color:#756f68;font-size:13px">Your demo order <b>${id}</b> has been placed. We'll show a tracking timeline for it next.</p><button class="btn btn-dark" onclick="closeAll();showTracking('${id}')">Track order</button></div>`;$$('.checkout-steps span').forEach(s=>s.classList.remove('active'));}
function showTracking(id){closeAll();$('#overlay').style.display='block';$('#quizModal').classList.add('open');$('#quizBody').innerHTML=`<p class="eyebrow">ORDER ${id}</p><h2>On its way to you.</h2><div style="border-left:2px solid #c9b18e;margin:25px 0 25px 10px;padding-left:22px"><p><b>✓ Order confirmed</b><br><small>Just now</small></p><p><b>✓ Packed with care</b><br><small>Expected within 1 day</small></p><p><b>○ Shipped</b><br><small>Expected within 2 days</small></p><p><b>○ Delivered</b><br><small>Expected within 3–5 days</small></p></div><button class="btn btn-dark full" onclick="closeAll()">Continue shopping</button>`}
function toggleWish(b){b.textContent=b.textContent==='♡'?'♥':'♡';toast(b.textContent==='♥'?'Saved to wishlist':'Removed from wishlist')}
function search(q){const r=$('#searchResults');let list=products.filter(p=>(p.name+' '+p.type+' '+p.cat+' '+p.tags.join(' ')).toLowerCase().includes(q.toLowerCase())).slice(0,8);r.innerHTML=list.map(p=>`<div class="search-result" onclick="addToCart(${p.id});closeAll()"><img src="${p.img}"><div><b>${p.name}</b><small style="display:block;color:#9b9188;margin-top:5px">${p.type} · ${money(p.price)}</small></div></div>`).join('')||'<p style="color:#999;padding:25px 0">No pieces found. Try “ring”, “gold”, “men” or “gift”.</p>'}
function chatReply(text){text=text.toLowerCase();if(text.includes('shipping'))return 'Orders over ₹2,999 get free shipping in this demo. Standard delivery is shown as ₹99 and usually takes 3–5 business days.';if(text.includes('return'))return 'Eligible unused pieces can be returned within 7 days in this demo. Keep the packaging intact for the smoothest return.';if(text.includes('payment'))return 'Checkout supports UPI, cards and cash on delivery in this demo. No real payment is processed.';if(text.includes('gift'))return 'Try the Gift filter or the jewellery sets. Every order is designed to arrive gift-ready.';if(text.includes('ring'))return 'For rings, our style quiz can narrow the collection. You can also search “ring” above.';return 'I can help with products, shipping, returns, payments, gifts and order tracking. Try one of the quick questions below.'}
function sendChat(msg){if(!msg)return;let box=$('#chatMessages');box.insertAdjacentHTML('beforeend',`<div class="user">${msg}</div><div class="bot">${chatReply(msg)}</div>`);box.scrollTop=box.scrollHeight}
$$('.filter').forEach(b=>b.addEventListener('click',()=>setFilter(b.dataset.filter)));$$('[data-filter]').forEach(b=>b.addEventListener('click',()=>setFilter(b.dataset.filter)));$('#cartBtn').onclick=openDrawer;$('#accountBtn').onclick=openAuth;$('#styleQuizBtn').onclick=openQuiz;$('#offerBtn').onclick=()=>{setFilter('gift');toast('Gift-ready pieces selected')};$('#checkoutBtn').onclick=checkout;$('#showMoreBtn').onclick=()=>{window.showAll=true;renderProducts();$('#showMoreBtn').style.display='none'};$('#couponBtn').onclick=()=>{let v=$('#couponInput').value.trim().toUpperCase();if(v==='WELCOME10'){let sub=cart.reduce((a,x)=>a+products.find(p=>p.id===x.id).price*x.qty,0);coupon=Math.round(sub*.1);renderCart();toast('WELCOME10 applied — 10% off')}else toast('Try WELCOME10')};$('#overlay').onclick=closeAll;$$('[data-close]').forEach(b=>b.onclick=closeAll);$('#searchBtn').onclick=()=>{$('#searchPanel').classList.add('open');$('#searchInput').focus()};$('#searchClose').onclick=()=>$('#searchPanel').classList.remove('open');$('#searchInput').oninput=e=>search(e.target.value);$('#mobileMenu').onclick=()=>$('#mainNav').classList.toggle('open');$('#subscribeBtn').onclick=()=>{let v=$('#emailInput').value;if(v.includes('@'))toast('You are on the list ✦');else toast('Enter a valid email')};$('#chatToggle').onclick=()=>$('#chatWindow').classList.toggle('open');$('#chatClose').onclick=()=>$('#chatWindow').classList.remove('open');$('#chatSend').onclick=()=>{let i=$('#chatInput');sendChat(i.value);i.value=''};$('#chatInput').onkeydown=e=>{if(e.key==='Enter'){$('#chatSend').click()}};$$('[data-chat]').forEach(b=>b.onclick=()=>sendChat(b.dataset.chat));$('#trackLink').onclick=e=>{e.preventDefault();let id='AU128450';showTracking(id)};$$('.tab').forEach(t=>t.onclick=()=>{$$('.tab').forEach(x=>x.classList.remove('active'));t.classList.add('active');$('#loginForm').classList.toggle('hidden',t.dataset.auth!=='login');$('#signupForm').classList.toggle('hidden',t.dataset.auth!=='signup')});$('#loginForm').onsubmit=e=>{e.preventDefault();toast('Demo login successful');closeAll()};$('#signupForm').onsubmit=e=>{e.preventDefault();toast('Account created — welcome to Aurum ✦');closeAll()};
renderProducts();renderCart();
